// <auto-generated />
using BlazorProjectApp1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorProjectApp1.Data.Migrations
{
    [DbContext(typeof(ProjectDBContext))]
    [Migration("20250404151554_AddImageToPost")]
    partial class AddImageToPost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("BlazorProjectApp1.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "Content for post 1",
                            Title = "Post 1"
                        },
                        new
                        {
                            PostId = 2,
                            Content = "Content for post 2",
                            Title = "Post 2"
                        },
                        new
                        {
                            PostId = 3,
                            Content = "Content for post 3",
                            Title = "Post 3"
                        },
                        new
                        {
                            PostId = 4,
                            Content = "Content for post 4",
                            Title = "Post 4"
                        },
                        new
                        {
                            PostId = 5,
                            Content = "Content for post 5",
                            Title = "Post 5"
                        },
                        new
                        {
                            PostId = 6,
                            Content = "Content for post 6",
                            Title = "Post 6"
                        });
                });

            modelBuilder.Entity("BlazorProjectApp1.Entities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.ToTable("UserAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
