name: SecOps Pipeline

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    types: [ completed ]

permissions:
  contents: read
  security-events: write

jobs:
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Install Dependency Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip
          unzip dependency-check-12.1.0-release.zip
          chmod +x dependency-check/bin/dependency-check.sh

      - name: Run Dependency Check
        run: |
          ./dependency-check/bin/dependency-check.sh \
            --project "BlazorProjectApp1-SecScan" \
            --out reports \
            --scan BlazorProjectApp1 \
            --nvdApiKey="${{ secrets.NVDAPIKEY }}"

      - name: Dependency Check Summary
        run: |
          echo "HIGH AND CRITICAL VULNERABILITIES FOUND"
          grep -iE "(CRITICAL|HIGH)" reports/dependency-check-report.html \
            || echo "→ No High or Critical found in dependency-check-report.html"
            
      # JSON processor used to read array for how many leaks found. 
      # Enforce Vulnerability Block will read the JSON and returns found leaks blocking only if gitleaks JSON shows leaks.
      - name: Install JQ
        run: |
          sudo apt-get update && sudo apt-get install -y jq

      - name: Install Gitleaks
        run: |
          curl -sSfL https://github.com/gitleaks/gitleaks/releases/download/v8.26.0/gitleaks_8.26.0_linux_x64.tar.gz \
            -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz
          chmod +x gitleaks
          mv gitleaks /usr/local/bin/

      - name: Run Gitleaks Secret Scan
        run: gitleaks detect --source . --redact --report-path gitleaks-report.json

      - name: Gitleaks Secret Scan Report
        run: |
          echo "GIT LEAKS SECRET SCAN REPORT"
          cat gitleaks-report.json

      - name: Enforce Vulnerability Block
        run: |
          dotnet list package --vulnerable || true
          # Block on any high or critical detections from OWASP d ependency check.
          if grep -qE "(CRITICAL|HIGH)" reports/dependency-check-report.html; then
            echo "!!!FAIL!!! Critical vulnerabilities detected blocking merge."
            exit 1
          fi
          leaks=$(jq 'length' gitleaks-report.json)
          if [ "$leaks" -gt 0 ]; then
            echo "!!!FAIL!!! Found $leaks secret leak(s) blocking merge."
            exit 1
          fi

      - name: Confirm SecOps Passed
        run: echo "!!!PASS!! SecOps checks completed without issue."
