# This workflow analyses a dotnet project using SonarQube-Cloud
# For more info: https://docs.sonarsource.com/sonarqube-cloud/
name: SonarQube-Cloud

on:
  push:
    # Triggers on push to main branch.
    branches:
      - main

jobs:
  build:
    name: SonarQube-Cloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Sonar requires the full GitHub history for tracking and analyses.
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # CLI tool installed for project analyses.
      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin SonarQube-Cloud Analysis
        run: |
          export PATH="$PATH:/home/runner/.dotnet/tools"
          dotnet-sonarscanner begin \
            /k:"amur123_BlazorProjectApp1" \
            /o:"amur123" \
            /d:sonar.token="${{ secrets.githubsonartoken }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.opencover.reportsPaths="CoverageReports/coverage.opencover.xml"

      # Restores Builds the solution to get ready for tests and analyses.
      - name: Restore and Build
        run: |
          dotnet restore
          dotnet build --no-incremental

      # Runs tests and collects coverage info.
      # Tells the test runner to use Coverlet for OpenCover output.
      - name: Run Tests and Collect Cobertura
        run: |
          dotnet test BlazorProjectApp1.Tests/BlazorProjectApp1.Tests.csproj \
            --no-build \
            --collect:"XPlat Code Coverage"

      - name: Convert Cobertura to OpenCover
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          reportgenerator \
            -reports:**/TestResults/*/coverage.cobertura.xml \
            -targetdir:CoverageReports \
            -reporttypes:opencover
          echo "Converted report at CoverageReports/coverage.opencover.xml"

      - name: Debug Find Converted Report
        run: |
          echo "--- Locating CoverageReports/coverage.opencover.xml ---"
          find CoverageReports -type f
            
      - name: Debug Show Layout
        run: |
          echo "--- Layout ---"
          find . -maxdepth 3 -type f -printf '  %P\n'

      - name: Debug Find coverage.opencover.xml
        run: |
          echo "--- Find coverage files ---"
          find . -type f -name "coverage.opencover.xml"

      # Finishes the scan and uploads results to SonarQube.
      - name: End SonarQube-Cloud Analysis
        run: dotnet-sonarscanner end /d:sonar.token="${{ secrets.githubsonartoken }}"
